import { Dimensions, Platform, StyleSheet } from 'react-native'
import { colors as themeColors } from '../theme/designTokens'

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window')

/** Matches AIPlanScreen.js SHEET_VISIBLE_EXPANDED for sheet chrome height */
const SHEET_VISIBLE_EXPANDED = 0.94
const SHEET_HEIGHT = SCREEN_HEIGHT * SHEET_VISIBLE_EXPANDED

const TILE_WIDTH = (SCREEN_WIDTH - 48 - 24) / 3

export const ITIN_GRID_GAP = 10
export const ITIN_CONTENT_GUTTER = 32
export const ITIN_GRID_TILE = Math.floor(((SCREEN_WIDTH - ITIN_CONTENT_GUTTER - ITIN_GRID_GAP) / 2) * 0.88)
export const ITIN_SLIDER_TILE = Math.floor((SCREEN_WIDTH - ITIN_CONTENT_GUTTER) * 0.38)

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  topBarWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 8,
    zIndex: 100,
  },
  /** Same width as searchButton so the icon row sits on the visual center line */
  topBarBalanceSpacer: {
    width: 44,
    height: 44,
  },
  planMiniNavRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 1,
    gap: 2,
  },
  planMiniNavBtn: {
    paddingHorizontal: 6,
    paddingVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 30,
  },
  planMiniNavLogo: {
    width: 18,
    height: 18,
    borderRadius: 9,
  },
  searchButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({ ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 8 }, android: { elevation: 4 } }),
  },
  searchModalRoot: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  searchModalHeadingWrap: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 4,
    alignItems: 'center',
  },
  searchModalHeading: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.3,
    textAlign: 'center',
  },
  searchModalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 10,
  },
  searchModalSearchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 4 },
      android: { elevation: 2 },
    }),
  },
  searchModalSearchIcon: {
    marginRight: 10,
  },
  searchModalSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#0F172A',
    paddingVertical: 0,
    minHeight: 22,
  },
  searchModalSearchClear: {
    padding: 2,
    marginLeft: 4,
  },
  searchModalCloseBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    flexShrink: 0,
  },
  searchModalLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  searchModalLoadingText: {
    fontSize: 15,
    color: '#64748B',
    fontWeight: '500',
  },
  searchModalScroll: { flex: 1 },
  searchModalContent: {
    paddingHorizontal: 16,
    paddingBottom: 40,
    paddingTop: 8,
  },
  searchModalSection: {
    marginBottom: 24,
  },
  searchModalSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  searchModalSectionIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchModalSectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  searchModalEmpty: {
    fontSize: 14,
    color: '#94A3B8',
    fontWeight: '500',
    fontStyle: 'italic',
  },
  searchModalHorizontalContent: {
    flexDirection: 'row',
    gap: 14,
    paddingRight: 16,
  },
  searchModalClientCard: {
    alignItems: 'center',
    width: 76,
  },
  searchModalClientCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAFBFC',
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
      android: { elevation: 3 },
    }),
  },
  searchModalClientImage: {
    width: '100%',
    height: '100%',
  },
  searchModalClientName: {
    fontSize: 11,
    fontWeight: '600',
    color: '#334155',
    textAlign: 'center',
    marginTop: 6,
    maxWidth: 76,
    lineHeight: 14,
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: SHEET_HEIGHT,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 16,
    overflow: 'hidden',
  },
  /** Plan results: opaque canvas (matches list) so map never shows through drag area, overscroll, or safe-area inset */
  sheetPlanResultsTint: {
    backgroundColor: '#F3EBED',
  },
  /** Step 3: avoid clipping first list rows (FlatList + transform + overflow hidden + radius is flaky on iOS) */
  sheetPlanOverflowVisible: {
    overflow: 'visible',
  },
  /** Full-width touch target for resizing the bottom sheet (compact strip; pan hitSlop widens taps) */
  sheetDragArea: {
    width: '100%',
    minHeight: 44,
    paddingTop: 6,
    paddingBottom: 6,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  grabber: { width: 32, height: 4, borderRadius: 2, backgroundColor: '#CBD5E1' },
  sheetDragHint: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },

  // Past plans (step 0) — compact, Bump-style
  pastPlansStepWrap: { flex: 1, minHeight: 0 },
  pastPlansScroll: { flex: 1, minHeight: 0 },
  d0ScrollContent: { paddingHorizontal: 20, paddingBottom: 20, paddingTop: 10 },
  d0CtaRow: {
    borderRadius: 20,
    overflow: 'hidden',
    marginTop: 0,
    marginBottom: 14,
    ...Platform.select({
      ios: { shadowColor: themeColors.primary, shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.28, shadowRadius: 14 },
      android: { elevation: 7 },
    }),
  },
  d0CtaGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: 20,
  },
  d0CtaLogoWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.4)',
    overflow: 'hidden',
    marginRight: 14,
  },
  d0CtaLogo: {
    width: 40,
    height: 40,
  },
  d0CtaLeft: { flex: 1 },
  d0CtaTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFF',
    letterSpacing: -0.4,
    marginBottom: 2,
  },
  d0CtaSub: {
    fontSize: 13,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.8)',
  },
  d0CtaArrow: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  d0SectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  d0SectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  d0SectionCount: {
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  d0SectionCountText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#64748B',
  },
  d0PlanCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 8,
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.03, shadowRadius: 6 },
      android: { elevation: 1 },
    }),
  },
  d0PlanIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: `${themeColors.primary}10`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  d0PlanInfo: { flex: 1 },
  d0PlanName: { fontSize: 15, fontWeight: '700', color: '#0F172A', marginBottom: 2 },
  d0PlanMeta: { fontSize: 13, color: '#94A3B8', fontWeight: '500' },
  d0ShareRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
  },
  d0ShareBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  d0ShareBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
  },
  d0CopyHint: {
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '800',
    color: themeColors.primary,
    marginTop: 8,
  },

  // Drawer page header — three-column row so center title is truly centered
  drawerPageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 4,
    marginBottom: 8,
    minHeight: 48,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15,23,42,0.06)',
  },
  drawerPageHeaderCenter: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  drawerPageHeaderSpacer: { width: 40, height: 40 },
  drawerPageHeaderTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.35,
    textAlign: 'center',
  },
  drawerPageHeaderMeta: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: '600',
    color: '#94A3B8',
    textAlign: 'center',
    letterSpacing: 0.15,
  },

  // Grid tiles for preferences + food
  gridScroll: { flex: 1 },
  gridContent: { paddingHorizontal: 24, paddingBottom: 48 },
  gridRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 },
  gridTile: {
    width: TILE_WIDTH, aspectRatio: 1, borderRadius: 14, borderWidth: 2,
    borderColor: '#E2E8F0', backgroundColor: '#FFFFFF',
    justifyContent: 'center', alignItems: 'center',
    shadowColor: '#0F172A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 6, elevation: 2,
  },
  gridTileIcon: {
    width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginBottom: 6,
  },
  gridTileLabel: { fontSize: 12, fontWeight: '600', color: '#334155', textAlign: 'center' },

  fixedButtonWrap: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 12,
  },

  continueButton: {
    backgroundColor: themeColors.primary, paddingVertical: 14, borderRadius: 14,
    alignItems: 'center', justifyContent: 'center', marginTop: 16,
    ...Platform.select({ ios: { shadowColor: themeColors.primary, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.18, shadowRadius: 8 }, android: { elevation: 4 } }),
  },
  continueButtonDisabled: { backgroundColor: '#E2E8F0' },
  continueButtonText: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },

  // Generate button (food)
  generateButton: {
    flexDirection: 'row', backgroundColor: themeColors.primary, paddingVertical: 14, borderRadius: 14,
    alignItems: 'center', justifyContent: 'center', marginTop: 16, gap: 8,
    ...Platform.select({ ios: { shadowColor: themeColors.primary, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.18, shadowRadius: 8 }, android: { elevation: 4 } }),
  },
  generateButtonDisabled: { opacity: 0.8 },
  generateButtonText: { fontSize: 16, fontWeight: '700', color: '#FFFFFF' },

  // ── Results (step 3) — tinted canvas so new layout is obvious vs plain white ──
  resultsScroll: {
    flex: 1,
    backgroundColor: '#F3EBED',
  },
  resultsContent: {
    paddingBottom: 4,
    paddingHorizontal: 16,
    paddingTop: 8,
    backgroundColor: '#FFFFFF',
  },
  planListEndFooter: {
    paddingTop: 18,
    paddingBottom: 28,
    paddingHorizontal: 8,
    marginTop: 4,
  },
  planListEndFooterText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
    lineHeight: 17,
    textAlign: 'center',
    letterSpacing: 0.1,
  },
  planDraggableListContainer: {
    flex: 1,
    minHeight: 0,
    backgroundColor: '#F3EBED',
  },
  planRowEnterWrap: {
    width: '100%',
  },
  planDraggableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 4,
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4 },
      android: { elevation: 2 },
    }),
  },
  planDraggableRowActive: {
    borderColor: 'rgba(200,16,46,0.45)',
    shadowOpacity: 0.14,
    elevation: 6,
  },
  planRowDragHit: {
    paddingVertical: 8,
    paddingHorizontal: 2,
    justifyContent: 'center',
  },
  planRowMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  planRowThumb: {
    width: 48,
    height: 48,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F1F5F9',
  },
  planRowThumbImg: {
    width: '100%',
    height: '100%',
  },
  planRowThumbPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  planRowTextCol: {
    flex: 1,
    minWidth: 0,
  },
  planTimeChip: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginBottom: 4,
  },
  planTimeChipText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  planRowSpotTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  planRowRatingInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  planRowRatingInlineText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  planRowEnhanceBtn: {
    width: 76,
    paddingHorizontal: 6,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(200,16,46,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  planRowEnhanceBtnText: {
    fontSize: 10,
    fontWeight: '800',
    color: themeColors.primary,
    textAlign: 'center',
    lineHeight: 13,
  },
  stopDialogEnhanceWrap: {
    marginTop: 14,
    marginBottom: 4,
  },
  stopDialogEnhanceWide: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: 'rgba(200,16,46,0.08)',
    borderWidth: 1.5,
    borderColor: 'rgba(200,16,46,0.22)',
  },
  stopDialogEnhanceWideText: {
    fontSize: 15,
    fontWeight: '800',
    color: themeColors.primary,
  },

  // Loading (sheet fallback) — Bump-style fun
  loadingWrap: {
    flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24, paddingBottom: 40,
  },
  loadingBumpCard: {
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    width: '100%',
    maxWidth: 380,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(200,16,46,0.1)',
    ...Platform.select({ ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.1, shadowRadius: 24 }, android: { elevation: 8 } }),
  },
  loadingBumpIllustration: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  loadingBumpIllustrationBg: {
    width: 60,
    height: 60,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingBumpIllustrationTrail: {
    flexDirection: 'row',
    gap: 3,
    marginLeft: 6,
  },
  loadingBumpTrailDot: {
    height: 4,
    borderRadius: 2,
    backgroundColor: themeColors.primary,
  },
  loadingSpotPreviews: { maxHeight: 76, marginBottom: 14, overflow: 'hidden', width: '100%' },
  loadingSpotPreviewsContent: { paddingHorizontal: 4, gap: 10 },
  loadingSpotPreviewItem: { width: 64, alignItems: 'center' },
  loadingSpotPreviewImg: { width: 52, height: 52, borderRadius: 10 },
  loadingSpotPreviewPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 10,
    backgroundColor: themeColors.primaryMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingSpotPreviewName: { fontSize: 10, fontWeight: '600', color: '#64748B', marginTop: 4, textAlign: 'center' },
  loadingProgressBar: {
    width: '100%',
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(200,16,46,0.12)',
    marginBottom: 16,
    overflow: 'hidden',
  },
  loadingProgressFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: themeColors.primary,
  },
  loadingBumpTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: -0.2,
  },
  loadingBumpSub: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 18,
  },
  loadingBumpSteps: { gap: 10, width: '100%', paddingHorizontal: 4 },
  loadingBumpStep: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  loadingBumpDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(200,16,46,0.15)',
    borderWidth: 2,
    borderColor: 'rgba(200,16,46,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingBumpDotDone: {
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
  },
  loadingBumpStepText: { fontSize: 13, fontWeight: '600', color: '#64748B' },
  loadingBumpStepTextDone: { color: '#0F172A', fontWeight: '700' },
  loadingPulse: {
    width: 96, height: 96, borderRadius: 48, backgroundColor: themeColors.primaryMuted,
    alignItems: 'center', justifyContent: 'center', marginBottom: 28,
    borderWidth: 2, borderColor: themeColors.primaryMuted,
  },
  loadingTitle: { fontSize: 24, fontWeight: '800', color: '#0F172A', marginBottom: 8, letterSpacing: -0.4 },
  loadingSubtext: { fontSize: 16, color: '#475569', textAlign: 'center', marginBottom: 36, fontWeight: '600' },
  loadingSteps: { gap: 18, width: '100%', paddingHorizontal: 12 },
  loadingStepRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  loadingDot: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  loadingStepText: { fontSize: 16, color: '#334155', fontWeight: '600' },

  // Error
  errorWrap: { paddingHorizontal: 24, flex: 1, justifyContent: 'center' },
  errorCard: {
    alignItems: 'center',
    padding: 28,
    backgroundColor: 'rgba(220,38,38,0.06)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(220,38,38,0.15)',
  },
  errorIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(220,38,38,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  errorTitle: { fontSize: 18, fontWeight: '800', color: '#991B1B', marginBottom: 8 },
  errorText: { fontSize: 15, color: '#B91C1C', fontWeight: '600', lineHeight: 22, textAlign: 'center' },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 24,
    paddingVertical: 18,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: themeColors.primary,
    backgroundColor: themeColors.primaryMuted,
  },
  retryButtonText: { fontSize: 16, fontWeight: '700', color: themeColors.primary },
  emptyResults: { fontSize: 15, color: '#64748B', textAlign: 'center', paddingVertical: 32, fontWeight: '500' },

  successIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: themeColors.success,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: { shadowColor: '#10B981', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.5, shadowRadius: 20 },
      android: { elevation: 12 },
    }),
  },
  planStep3Body: {
    flex: 1,
    minHeight: 0,
    backgroundColor: '#F3EBED',
  },
  planContentFill: {
    flex: 1,
    minHeight: 0,
    backgroundColor: '#F3EBED',
  },
  planMastheadRoot: {
    flexShrink: 0,
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(226, 232, 240, 0.95)',
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8 },
      android: { elevation: 3 },
    }),
  },
  planMastheadTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  planMastheadBackBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(15,23,42,0.08)',
  },
  planMastheadTitleBlock: {
    flex: 1,
    minWidth: 0,
    paddingTop: 0,
    justifyContent: 'center',
  },
  planMastheadTitleLine: {
    marginTop: 0,
  },
  planMastheadTitleStrong: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.45,
  },
  planMastheadTitleSoft: {
    fontSize: 16,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: -0.35,
  },
  planMastheadMetaLine: {
    marginTop: 3,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.05,
  },
  planMastheadMetaEm: {
    fontSize: 12,
    fontWeight: '800',
    color: themeColors.primary,
  },
  planMastheadMetaSep: {
    fontSize: 12,
    fontWeight: '600',
    color: '#94A3B8',
  },
  planMastheadActions: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
    marginTop: 8,
  },
  iv2Eyebrow: {
    fontSize: 10,
    fontWeight: '800',
    color: '#94a3b8',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  iv2Headline: {
    marginTop: 4,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.65,
    lineHeight: 28,
  },
  iv2HeadlineLead: {
    color: '#0f172a',
    fontWeight: '900',
    letterSpacing: -0.65,
    fontSize: 24,
  },
  iv2HeadlineTrail: {
    color: '#64748b',
    fontWeight: '700',
    fontSize: 22,
    letterSpacing: -0.45,
  },
  iv2StatsLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    marginTop: 10,
    gap: 5,
  },
  iv2StatsEm: {
    fontSize: 17,
    fontWeight: '900',
    color: themeColors.primary,
    letterSpacing: -0.4,
  },
  iv2StatsWord: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
    marginRight: 2,
  },
  iv2StatsSep: {
    fontSize: 14,
    fontWeight: '500',
    color: '#cbd5e1',
    marginHorizontal: 2,
  },
  iv2Hint: {
    marginTop: 10,
    fontSize: 11,
    fontWeight: '600',
    color: '#94a3b8',
    lineHeight: 15,
  },
  iv2ActionRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    marginTop: 12,
  },
  iv2MapOutline: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: themeColors.primary,
    backgroundColor: '#FFFFFF',
  },
  iv2MapOutlineText: {
    fontSize: 14,
    fontWeight: '800',
    color: themeColors.primary,
    letterSpacing: 0.15,
  },
  iv2Seg: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: 'rgba(255,255,255,0.85)',
    overflow: 'hidden',
  },
  iv2SegBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iv2SegDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: '#e2e8f0',
  },
  iv2CopyToast: {
    marginTop: 6,
    fontSize: 11,
    fontWeight: '800',
    color: themeColors.primary,
    letterSpacing: 0.3,
  },

  iv2SectionHeadGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
    marginTop: 0,
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(15,23,42,0.08)',
  },
  iv2SectionIconSq: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.12, shadowRadius: 6 },
      android: { elevation: 3 },
    }),
  },
  iv2SectionHeadGridText: {
    flex: 1,
    minWidth: 0,
  },
  iv2SectionGridTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.25,
  },
  iv2SectionGridMeta: {
    marginTop: 1,
    fontSize: 11,
    fontWeight: '600',
    color: '#94a3b8',
    letterSpacing: 0.1,
  },

  iv2Grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: ITIN_GRID_GAP,
  },
  iv2SliderContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: ITIN_GRID_GAP,
    paddingRight: 24,
  },
  iv2GridTile: {
    aspectRatio: 1,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 10 },
      android: { elevation: 4 },
    }),
  },
  iv2GridTileInner: {
    flex: 1,
    borderRadius: 14,
    overflow: 'hidden',
    position: 'relative',
  },
  iv2GridTileImg: {
    ...StyleSheet.absoluteFillObject,
  },
  iv2GridTileImgEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  iv2GridTileTopRow: {
    position: 'absolute',
    top: 8,
    left: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  iv2GridTileNumBadge: {
    minWidth: 28,
    height: 28,
    paddingHorizontal: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iv2GridTileNumBadgeText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  iv2GridTileRating: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.95)',
  },
  iv2GridTileRatingText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0f172a',
  },
  iv2GridTileBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 10,
    paddingBottom: 10,
    paddingTop: 28,
    zIndex: 2,
  },
  iv2GridTileSpot: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.2,
    lineHeight: 17,
    textShadowColor: 'rgba(0,0,0,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  iv2GridTileExpandHint: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    zIndex: 3,
  },

  stopDialogKb: {
    flex: 1,
  },
  stopDialogRoot: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 6,
  },
  stopDialogDim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.58)',
  },
  stopDialogCard: {
    maxHeight: SCREEN_HEIGHT * 0.94,
    zIndex: 2,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 14 }, shadowOpacity: 0.28, shadowRadius: 32 },
      android: { elevation: 18 },
    }),
  },
  stopDialogHero: {
    width: '100%',
    alignSelf: 'stretch',
    backgroundColor: '#0f172a',
  },
  stopDialogBodyScroll: {
    maxHeight: SCREEN_HEIGHT * 0.52,
  },
  stopDialogScrollContent: {
    paddingBottom: 22,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  stopDialogHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  stopDialogHeaderMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    minWidth: 0,
  },
  stopDialogNumBadge: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopDialogNumText: {
    fontSize: 15,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  stopDialogTitleCol: {
    flex: 1,
    minWidth: 0,
  },
  stopDialogSpotTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0f172a',
    letterSpacing: -0.45,
    lineHeight: 27,
  },
  stopDialogRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 6,
  },
  stopDialogRatingText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#475569',
  },
  stopDialogClose: {
    marginTop: -4,
    marginRight: -4,
    padding: 4,
  },
  stopDialogSectionLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#94a3b8',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  stopDialogDescBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 18,
  },
  stopDialogDescText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#334155',
    lineHeight: 24,
  },
  stopDialogActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 4,
  },
  stopDialogBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    minHeight: 48,
  },
  stopDialogBtnPrimary: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 120,
    backgroundColor: themeColors.primary,
    ...Platform.select({
      ios: { shadowColor: themeColors.primary, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.25, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  stopDialogBtnPrimaryText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  stopDialogBtnGhost: {
    borderWidth: 1.5,
    borderColor: 'rgba(200,16,46,0.35)',
    backgroundColor: 'rgba(200,16,46,0.06)',
  },
  stopDialogBtnGhostText: {
    fontSize: 14,
    fontWeight: '800',
    color: themeColors.primary,
  },

  iv2Footer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginTop: 20,
    marginBottom: 12,
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  iv2FooterText: {
    flex: 1,
    fontSize: 11,
    fontWeight: '600',
    color: '#94a3b8',
    lineHeight: 16,
    letterSpacing: 0.15,
  },

  // ── Boarding pass hero (legacy) ──
  boardingPass: {
    backgroundColor: '#FFFFFF', borderRadius: 24, marginBottom: 28, overflow: 'hidden',
    borderWidth: 0,
    shadowColor: '#0F172A', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 24, elevation: 8,
  },
  bpTop: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 28, paddingTop: 26, paddingBottom: 22,
  },
  bpLabel: { fontSize: 12, fontWeight: '800', color: '#64748B', letterSpacing: 1.6 },
  bpValue: { fontSize: 28, fontWeight: '800', color: '#0F172A', marginTop: 6, letterSpacing: -0.5 },
  bpDivider: {
    width: 52, height: 52, borderRadius: 26, borderWidth: 2, borderColor: 'rgba(200,16,46,0.15)',
    backgroundColor: 'rgba(200,16,46,0.08)', alignItems: 'center', justifyContent: 'center',
  },
  bpDashedLine: {
    height: 1, marginHorizontal: 24,
    borderStyle: 'dashed', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 1,
  },
  bpBottom: {
    paddingHorizontal: 28, paddingVertical: 22,
  },
  bpBudgetWrap: { alignItems: 'center' },
  bpBudgetRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  bpBudgetTitle: { fontSize: 12, fontWeight: '800', color: '#475569', letterSpacing: 1.2, textTransform: 'uppercase' },
  bpBudgetAmount: { fontSize: 30, fontWeight: '900', color: themeColors.primary, letterSpacing: 0.5 },
  bpBudgetSub: { fontSize: 14, color: '#64748B', marginTop: 6, fontWeight: '600' },
  bpAdviceWrap: {
    flexDirection: 'row', alignItems: 'flex-start', gap: 12,
    backgroundColor: '#FFFBEB', borderTopWidth: 1, borderTopColor: '#FDE68A',
    paddingHorizontal: 26, paddingVertical: 20, borderBottomLeftRadius: 24, borderBottomRightRadius: 24,
  },
  bpAdviceText: { fontSize: 15, color: '#92400E', lineHeight: 22, flex: 1, fontStyle: 'italic', fontWeight: '600' },

  // ── Itinerary list (flat rows + iv2 masthead / sections) ──
  bumpItinSection: { marginBottom: 14 },
  bumpItinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
  },
  bumpItinNumCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  bumpItinNumText: { fontSize: 12, fontWeight: '800', color: '#FFFFFF' },
  bumpItinThumbWrap: {
    position: 'relative',
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: 'hidden',
    marginRight: 0,
  },
  bumpItinThumb: {
    width: '100%',
    height: '100%',
  },
  bumpItinThumbPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bumpItinRatingPill: {
    position: 'absolute',
    bottom: 4,
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.95)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  bumpItinRatingPillText: { fontSize: 9, fontWeight: '800', color: '#0F172A' },
  bumpItinSummary: { flex: 1, minWidth: 0 },
  bumpItinName: { fontSize: 15, fontWeight: '800', color: '#0F172A', marginBottom: 3, letterSpacing: -0.2 },
  bumpItinReason: { fontSize: 12, color: '#64748B', lineHeight: 16 },
  bumpItinActionRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 6 },
  bumpItinActionIcon: { padding: 2 },
  bumpItinChevron: { marginLeft: 4 },
  bumpItinExpanded: {
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingHorizontal: 12,
    paddingBottom: 12,
    paddingTop: 10,
  },
  bumpItinExpandedImageWrap: {
    width: '100%',
    height: 100,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#F8FAFC',
    marginBottom: 10,
  },
  bumpItinExpandedScroll: { width: '100%', height: 100 },
  bumpItinExpandedScrollContent: { flexGrow: 1 },
  bumpItinExpandedSlide: {
    width: SCREEN_WIDTH - 32,
    height: 100,
    position: 'relative',
  },
  bumpItinExpandedPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bumpItinExpandedReason: {
    fontSize: 13,
    color: '#64748B',
    lineHeight: 20,
    marginBottom: 10,
  },
  bumpItinExpandedActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  bumpItinExpandedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  bumpItinExpandedBtnPrimary: {
    backgroundColor: themeColors.primary,
  },
  bumpItinExpandedBtnPrimaryText: { fontSize: 13, fontWeight: '700', color: '#FFFFFF' },
  bumpItinExpandedBtnSecondary: {
    backgroundColor: 'rgba(200,16,46,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(200,16,46,0.2)',
  },
  bumpItinExpandedBtnSecondaryText: { fontSize: 13, fontWeight: '600', color: themeColors.primary },

  // ── Itinerary section (legacy) ──
  itinSection: { marginBottom: 16 },

  secBanner: {
    flexDirection: 'row', alignItems: 'center', borderRadius: 20, paddingVertical: 16,
    paddingHorizontal: 20, marginBottom: 16,
  },
  secIconCircle: {
    width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center',
  },
  secBannerText: { flex: 1, marginLeft: 16 },
  secBannerTitle: { fontSize: 21, fontWeight: '800', letterSpacing: -0.3 },
  secBannerSub: { fontSize: 14, fontWeight: '600', opacity: 0.85, marginTop: 2 },
  secBannerCount: { fontSize: 14, fontWeight: '700' },

  // ── Destination row (number + card) ──
  destRow: { flexDirection: 'row', paddingLeft: 6 },

  destLeft: { width: 40, alignItems: 'center', paddingTop: 18 },
  destNumCircle: {
    width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', zIndex: 2,
  },
  destNum: { fontSize: 14, fontWeight: '800', color: '#FFFFFF' },
  destConnector: { flex: 1, width: 2, borderRadius: 1, marginTop: 8 },

  // Card
  destCard: {
    flex: 1, backgroundColor: '#FFFFFF', borderRadius: 22, marginLeft: 16, marginBottom: 16,
    overflow: 'hidden', borderWidth: 0,
    shadowColor: '#0F172A', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.08, shadowRadius: 16, elevation: 6,
  },
  destStrip: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: 16, paddingVertical: 10,
  },
  destStripText: { fontSize: 11, fontWeight: '800', letterSpacing: 1.2 },
  destBody: {
    flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 14, paddingBottom: 10,
  },
  destIconBox: {
    width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginRight: 16,
  },
  destName: { flex: 1, fontSize: 18, fontWeight: '700', color: '#0F172A', lineHeight: 24 },
  destReasonWrap: {
    flexDirection: 'row', marginHorizontal: 16, marginBottom: 18, marginTop: 8,
    backgroundColor: '#FFFBEB', borderRadius: 16, padding: 16, gap: 12,
  },
  destReasonQuote: { marginTop: 2 },
  destReasonText: { flex: 1, fontSize: 15, color: '#78350F', lineHeight: 22, fontStyle: 'italic', fontWeight: '600' },
  destARBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(200,16,46,0.08)',
    borderRadius: 12,
  },
  destARBtnText: { fontSize: 14, fontWeight: '700', color: themeColors.primary },

  // ── Passport stamp footer (legacy) ──
  stampFooter: { alignItems: 'center', marginTop: 28, paddingBottom: 12 },
  stampCircle: {
    width: 96, height: 96, borderRadius: 48, borderWidth: 2.5, borderColor: themeColors.primary,
    alignItems: 'center', justifyContent: 'center', marginBottom: 16,
    borderStyle: 'dashed',
  },
  stampTop: { fontSize: 10, fontWeight: '800', color: themeColors.primary, letterSpacing: 2 },
  stampBottom: { fontSize: 9, fontWeight: '700', color: themeColors.primary, letterSpacing: 1.5, marginTop: 2 },
  stampTagline: { fontSize: 16, fontWeight: '600', color: '#475569', fontStyle: 'italic' },

  // ── Map pins (legacy, kept for reference) ──
  mapPinWrap: { alignItems: 'center' },
  mapPinRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  mapPin: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 9, paddingVertical: 6, borderRadius: 16,
    shadowColor: '#0F172A', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 6,
  },
  mapPinNum: { fontSize: 12, fontWeight: '800', color: '#FFFFFF' },
  mapPinLabel: {
    maxWidth: 120, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, borderWidth: 1.5,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4, elevation: 4,
  },
  mapPinLabelText: { fontSize: 12, fontWeight: '700' },
  mapPinArrow: {
    alignSelf: 'center', width: 0, height: 0,
    borderLeftWidth: 6, borderRightWidth: 6, borderTopWidth: 8,
    borderLeftColor: 'transparent', borderRightColor: 'transparent',
  },

  // ── Animated place markers (profile image + entrance animation) ──
  animatedMarkerWrap: {
    alignItems: 'center',
  },
  animatedMarkerPulseRing: {
    position: 'absolute',
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    top: 2,
  },
  animatedMarkerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    overflow: 'hidden',
    backgroundColor: '#FFF',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  animatedMarkerImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  animatedMarkerIconBg: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  animatedMarkerBadge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  animatedMarkerBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFF',
  },
  animatedMarkerLabel: {
    marginTop: 6,
    maxWidth: 110,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1.5,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 4,
  },
  animatedMarkerLabelText: {
    fontSize: 12,
    fontWeight: '700',
  },
  animatedMarkerArrow: {
    alignSelf: 'center',
    width: 0,
    height: 0,
    marginTop: 2,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },

  // ── Map marker details bottom sheet (slides up from bottom) ──
  markerBottomSheetRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1100,
    elevation: 1100,
    justifyContent: 'flex-end',
  },
  markerBottomSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0F172A',
    zIndex: 1,
  },
  markerBottomSheetPanel: {
    zIndex: 2,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingTop: 6,
    paddingHorizontal: 0,
    overflow: 'hidden',
    maxHeight: SCREEN_HEIGHT * 0.68,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: -4 }, shadowOpacity: 0.14, shadowRadius: 18 },
      android: { elevation: 26 },
    }),
  },
  markerBottomSheetGrab: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E2E8F0',
    marginBottom: 10,
    marginTop: 2,
  },
  markerBottomSheetHeroWrap: {
    marginHorizontal: 14,
    borderRadius: 18,
    overflow: 'hidden',
    height: Math.min(196, SCREEN_HEIGHT * 0.26),
    backgroundColor: '#E2E8F0',
  },
  markerBottomSheetHeroImg: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  markerBottomSheetHeroPlaceholder: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerBottomSheetHeroPlaceholderIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  markerBottomSheetHeroScrim: {
    ...StyleSheet.absoluteFillObject,
  },
  markerBottomSheetHeroClose: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 4,
  },
  markerBottomSheetHeroCloseInner: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.38)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  markerBottomSheetHeroFoot: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingBottom: 14,
    paddingTop: 28,
  },
  markerBottomSheetHeroTypePill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    marginBottom: 8,
  },
  markerBottomSheetHeroTypeIcon: {
    marginRight: 6,
  },
  markerBottomSheetHeroTypeText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  markerBottomSheetHeroTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.5,
    lineHeight: 28,
    textShadowColor: 'rgba(0,0,0,0.45)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  markerBottomSheetHeroTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
  },
  markerBottomSheetHeroTimeText: {
    fontSize: 14,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.95)',
  },
  markerBottomSheetReasonCard: {
    marginHorizontal: 14,
    marginTop: 14,
    marginBottom: 4,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  markerBottomSheetReasonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  markerBottomSheetReasonTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  markerBottomSheetReasonScroll: {
    maxHeight: SCREEN_HEIGHT * 0.18,
  },
  markerBottomSheetReason: {
    fontSize: 14,
    lineHeight: 22,
    color: '#475569',
    fontWeight: '500',
  },
  markerBottomSheetActions: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 6,
  },
  markerBottomSheetActionsHeading: {
    fontSize: 12,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 10,
    marginLeft: 2,
  },
  markerBottomSheetActionGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  markerBottomSheetActionCell: {
    flex: 1,
    minWidth: 88,
    borderRadius: 16,
    overflow: 'hidden',
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  markerBottomSheetActionGradient: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
    gap: 8,
    minHeight: 88,
  },
  markerBottomSheetActionGradientLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },

  // ── Map scanning overlay (Hang tight) — route tracing + radar ──
  mapScanningOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
  },
  mapScanningRadarCenter: {
    position: 'absolute',
    left: SCREEN_WIDTH / 2 - 100,
    top: SCREEN_HEIGHT / 2 - 100,
    width: 200,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapScanningRadarRing: {
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: 'rgba(200,16,46,0.6)',
    backgroundColor: 'rgba(200,16,46,0.06)',
  },
  mapScanningLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: 'rgba(200,16,46,0.55)',
    shadowColor: themeColors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  mapRoutePath: {
    ...StyleSheet.absoluteFillObject,
  },
  mapRouteSegWrap: {
    position: 'absolute',
    left: 30,
    top: 70,
    width: SCREEN_WIDTH - 90,
    height: 4,
    overflow: 'hidden',
    backgroundColor: 'rgba(200,16,46,0.15)',
    borderRadius: 2,
  },
  mapRouteSegWrap2: {
    position: 'absolute',
    right: 50,
    top: 70,
    width: 4,
    height: 130,
    overflow: 'hidden',
    backgroundColor: 'rgba(200,16,46,0.15)',
    borderRadius: 2,
  },
  mapRouteSegWrap3: {
    position: 'absolute',
    left: 40,
    top: 195,
    width: SCREEN_WIDTH - 90,
    height: 4,
    overflow: 'hidden',
    backgroundColor: 'rgba(200,16,46,0.15)',
    borderRadius: 2,
  },
  mapRouteSegWrap4: {
    position: 'absolute',
    left: 40,
    top: 195,
    width: 4,
    height: 130,
    overflow: 'hidden',
    backgroundColor: 'rgba(200,16,46,0.15)',
    borderRadius: 2,
  },
  mapRouteSegWrap5: {
    position: 'absolute',
    left: 30,
    top: 320,
    width: SCREEN_WIDTH - 80,
    height: 4,
    overflow: 'hidden',
    backgroundColor: 'rgba(200,16,46,0.15)',
    borderRadius: 2,
  },
  mapRouteSeg: {
    position: 'absolute',
    left: 0,
    top: 0,
    backgroundColor: 'rgba(200,16,46,0.7)',
  },
  mapRouteSeg1: { width: SCREEN_WIDTH - 90, height: 4, borderRadius: 2 },
  mapRouteSeg2: { width: 4, height: 130, borderRadius: 2 },
  mapRouteSeg3: { width: SCREEN_WIDTH - 90, height: 4, borderRadius: 2 },
  mapRouteSeg4: { width: 4, height: 130, borderRadius: 2 },
  mapRouteSeg5: { width: SCREEN_WIDTH - 80, height: 4, borderRadius: 2 },
  mapRouteDotGlow: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(200,16,46,0.35)',
  },
  mapRouteDot: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: themeColors.primary,
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.95)',
    shadowColor: themeColors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 10,
  },

  // ── Bump-style UI ──
  bumpHeaderWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 50,
  },
  bumpHeaderCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    gap: 10,
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  bumpHeaderTextWrap: { flex: 1 },
  bumpHeaderTitle: { fontSize: 15, fontWeight: '700', color: '#0F172A' },
  bumpHeaderAddress: { fontSize: 13, color: '#64748B', marginTop: 2, fontWeight: '500' },
  bumpBottomCardWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 50,
  },
  bumpBottomCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: themeColors.primary,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    ...Platform.select({
      ios: { shadowColor: themeColors.primary, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.2, shadowRadius: 8 },
      android: { elevation: 6 },
    }),
  },
  bumpBottomCardLeft: {
    flex: 1,
  },
  bumpBottomCardEta: {
    fontSize: 17,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  bumpBottomCardSub: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.9)',
    marginTop: 2,
    fontWeight: '600',
  },
  bumpBottomCardStop: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
  },
  bumpBottomCardStopText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  bumpBottomCardExpand: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 8,
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
      android: { elevation: 4 },
    }),
  },
  bumpBottomCardExpandText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0F172A',
    flex: 1,
  },

  // ── Spot detail card (legacy, kept for fallback) ──
  spotDetailWrap: {
    position: 'absolute', left: 20, right: 20, zIndex: 100,
  },
  spotDetailCard: {
    backgroundColor: '#FFFFFF', borderRadius: 22, overflow: 'hidden',
    shadowColor: '#0F172A', shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.18, shadowRadius: 28, elevation: 16,
  },
  spotDetailAccent: { height: 5 },
  spotDetailBody: { padding: 20 },
  spotDetailRow1: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 14 },
  spotDetailStep: {
    width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginRight: 14, marginTop: 2,
  },
  spotDetailStepText: { fontSize: 15, fontWeight: '900', color: '#FFF' },
  spotDetailNameWrap: { flex: 1, marginRight: 10 },
  spotDetailName: { fontSize: 18, fontWeight: '800', color: '#0F172A', lineHeight: 24, marginBottom: 8 },
  spotDetailTags: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  spotDetailTag: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10,
  },
  spotDetailTagText: { fontSize: 12, fontWeight: '700' },
  spotDetailDot: { fontSize: 14, color: '#E2E8F0' },
  spotDetailTime: { fontSize: 13, fontWeight: '600', color: '#94A3B8' },
  spotDetailReason: { fontSize: 15, color: '#475569', lineHeight: 22, marginBottom: 16 },
  spotDetailBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8,
    paddingVertical: 15, borderRadius: 16,
  },
  spotDetailBtnText: { fontSize: 16, fontWeight: '700', color: '#FFF' },

  // ── Plan modal (Home AI design) ──
  planModalRoot: { flex: 1, backgroundColor: 'transparent' },
  planModalBackdropWrap: { ...StyleSheet.absoluteFillObject },
  planModalBackdropDim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.12)' },
  planModalContentWrap: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 56 : 44,
    paddingBottom: 20,
    alignItems: 'stretch',
  },
  planModalPresenceLayer: { flex: 1, width: '100%', alignSelf: 'stretch' },
  // ── Plan modal hero & chips ──
  pmHero: {
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 8,
    paddingHorizontal: 16,
  },
  pmStepBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    marginBottom: 16,
  },
  pmStepBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.78)',
    letterSpacing: 1.5,
  },
  pmStepDots: {
    flexDirection: 'row',
    gap: 4,
  },
  pmStepDotSmall: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  pmStepDotSmallActive: {
    backgroundColor: '#FFFFFF',
    ...Platform.select({
      ios: { shadowColor: '#FFF', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.5, shadowRadius: 4 },
      android: {},
    }),
  },
  pmTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: -0.8,
    lineHeight: 34,
    marginBottom: 8,
    ...Platform.select({
      ios: {
        textShadowColor: 'rgba(0,0,0,0.4)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 14,
      },
      android: { elevation: 2 },
    }),
  },
  pmSub: {
    fontSize: 15,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.65)',
    textAlign: 'center',
    lineHeight: 21,
    letterSpacing: 0.1,
    marginBottom: 12,
    maxWidth: 280,
  },
  pmSelectedPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.42)',
  },
  pmSelectedText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  pmChipsWrap: {
    flex: 1,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  pmChipsScroll: { flex: 1 },
  pmChipsScrollContent: { paddingBottom: 16, paddingHorizontal: 2 },
  pmChipsPanel: {
    width: '100%',
    borderRadius: 22,
    paddingVertical: 14,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(0,0,0,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.2, shadowRadius: 20 },
      android: { elevation: 4 },
    }),
  },
  pmChipsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
  },
  pmChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingVertical: 11,
    paddingHorizontal: 15,
    borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.97)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
    ...Platform.select({
      ios: { shadowColor: '#1e0a0c', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.18, shadowRadius: 8 },
      android: { elevation: 3 },
    }),
  },
  pmChipSelected: {
    borderWidth: 2,
    ...Platform.select({
      ios: { shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.35, shadowRadius: 14 },
      android: { elevation: 8 },
    }),
  },
  pmChipIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(15,23,42,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pmChipText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e293b',
    letterSpacing: 0.1,
  },
  pmChipTextSelected: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  pmChipCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -2,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  ldWrap: {
    flex: 1,
    width: '100%',
  },
  ldScrollContent: {
    paddingHorizontal: 24,
    paddingTop: SCREEN_HEIGHT * 0.3,
    paddingBottom: 40,
    alignItems: 'center',
  },
  ldBodyNoScroll: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ldTopLoadingBlock: {
    width: '100%',
    alignItems: 'center',
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    justifyContent: 'flex-start',
  },
  ldStepsFooter: {
    width: '100%',
    flexShrink: 0,
    gap: 8,
    marginBottom: 4,
  },
  ldTitleSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  ldPlanLoadTitleBlock: {
    alignItems: 'center',
    marginBottom: 6,
    width: '100%',
  },
  ldTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: -0.8,
    lineHeight: 38,
    marginBottom: 6,
    ...Platform.select({
      ios: { textShadowColor: 'rgba(0,0,0,0.3)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 12 },
    }),
  },
  ldSub: {
    fontSize: 15,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.75)',
    textAlign: 'center',
    lineHeight: 21,
  },
  ldLoadingSub: {
    fontSize: 16,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.82)',
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 12,
    marginTop: 2,
  },
  ldSuccessCenter: {
    width: 160,
    height: 160,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  ldSheetHintCard: {
    width: '100%',
    maxWidth: 340,
    alignSelf: 'center',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    marginBottom: 20,
    gap: 8,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 20 },
      android: { elevation: 8 },
    }),
  },
  ldSheetHintTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0f172a',
    textAlign: 'center',
    letterSpacing: -0.4,
  },
  ldSheetHintSub: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 19,
  },
  lsSteps: {
    width: '100%',
    gap: 10,
    marginBottom: 12,
  },
  lsCard: {
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    padding: 16,
    overflow: 'hidden',
    position: 'relative',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
    }),
  },
  lsCardGlow: {
    position: 'absolute',
    top: -20,
    left: -20,
    right: -20,
    bottom: -20,
    borderRadius: 30,
    ...Platform.select({
      ios: { shadowColor: '#C8102E', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.4, shadowRadius: 20 },
    }),
  },
  lsCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  lsIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  lsRing: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
  },
  lsTextCol: { flex: 1 },
  lsStepName: {
    fontSize: 15,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.45)',
    marginBottom: 1,
  },
  lsStepNameDone: { color: '#FFFFFF' },
  lsStepNameActive: { color: '#FFFFFF', fontWeight: '800' },
  lsStepStatus: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.3)',
  },
  lsBarTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(255,255,255,0.14)',
    overflow: 'hidden',
    position: 'relative',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 2 },
    }),
  },
  lsBarFillWrap: {
    height: '100%',
    borderRadius: 5,
    overflow: 'hidden',
  },
  lsBarFill: {
    flex: 1,
    borderRadius: 5,
  },
  lsBarShimmer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 80,
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderRadius: 5,
  },
  ldFactCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    width: '100%',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 10,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
    }),
  },
  ldFactIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  ldFactContent: { flex: 1 },
  ldFactLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FACC15',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  ldFactText: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.75)',
    lineHeight: 18,
    fontWeight: '500',
  },
  planModalMarqueeMask: {
    width: '100%',
    overflow: 'hidden',
  },
  planModalBannerWrap: {
    width: '100%',
    overflow: 'hidden',
  },
  planModalBannerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  planModalPreviewScroll: {
    paddingLeft: 4,
    paddingRight: 24,
    gap: 12,
  },
  planModalPreviewCard: {
    width: 110,
    borderRadius: 18,
    marginRight: 12,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.3)',
    overflow: 'hidden',
    alignItems: 'center',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 12 },
      android: { elevation: 6 },
    }),
  },
  planModalPreviewImage: {
    width: '100%',
    height: 76,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  planModalPreviewIcon: {
    width: '100%',
    height: 76,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  planModalBannerName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  planModalBannerTag: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.85)',
    marginTop: 4,
    fontWeight: '500',
  },
  planModalPreviewCardLegacy: {
    width: 220,
    borderRadius: 18,
    marginRight: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  planModalPreviewImage: {
    width: '100%',
    height: 96,
  },
  planModalPreviewBody: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  planModalPreviewTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
    gap: 6,
  },
  planModalPreviewTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  planModalPreviewTagText: {
    fontSize: 11,
    fontWeight: '700',
  },
  planModalPreviewArea: {
    fontSize: 11,
    color: 'rgba(15,23,42,0.9)',
    fontWeight: '500',
  },
  planModalPreviewName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 4,
  },
  planModalPreviewSnippet: {
    fontSize: 13,
    color: '#1F2937',
    lineHeight: 18,
  },
  planModalPreviewPager: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  planModalPreviewDotRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  planModalPreviewDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(15,23,42,0.18)',
  },
  planModalPreviewDotActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#0F172A',
  },
  planModalPreviewCounter: {
    fontSize: 11,
    color: 'rgba(15,23,42,0.65)',
    fontWeight: '600',
  },
  planModalOptionsWrap: { flex: 1, width: '100%', maxWidth: 400, alignSelf: 'center' },
  planModalActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.28)',
  },
  planModalBackBtn: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.38)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  planModalContinueBtn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    overflow: 'hidden',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 12 },
      android: { elevation: 6 },
    }),
  },
  planModalBtnGradient: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  planModalContinueBtnText: { fontSize: 16, fontWeight: '800', color: '#FFFFFF', letterSpacing: 0.3 },
  planModalGenerateBtn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    overflow: 'hidden',
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.15, shadowRadius: 16 },
      android: { elevation: 8 },
    }),
  },
  planModalGenerateBtnText: { fontSize: 15, fontWeight: '800', color: '#FFFFFF', letterSpacing: 0.3 },
  optionCheckBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  doorOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9999,
    elevation: 9999,
  },
  doorHalf: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: SCREEN_WIDTH / 2,
    overflow: 'hidden',
  },
  doorLeft: {
    left: 0,
  },
  doorRight: {
    right: 0,
  },
  doorZigzag: {
    position: 'absolute',
    top: 0,
    left: SCREEN_WIDTH / 2,
    bottom: 0,
    zIndex: 2,
  },
  doorIconWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10000,
  },
  doorLogoShadow: {
    width: 124,
    height: 124,
    borderRadius: 62,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 14,
  },
  doorLogoImage: {
    width: 116,
    height: 116,
    borderRadius: 58,
  },
  doorFlagLabel: {
    marginTop: 16,
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 3,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0,0,0,0.4)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  categorySpinHudRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 115,
    elevation: 115,
    pointerEvents: 'box-none',
  },
  categorySpinHudBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0F172A',
    zIndex: 0,
  },
  categorySpinHudAnchor: {
    position: 'absolute',
    left: 0,
    zIndex: 2,
    width: 260,
    minHeight: 200,
    pointerEvents: 'box-none',
  },
  categorySpinFabGlowRing: {
    position: 'absolute',
    left: -8,
    top: -8,
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 2,
    borderColor: `${themeColors.primary}55`,
    backgroundColor: `${themeColors.primary}10`,
  },
  categorySpinSemiFabPress: {
    zIndex: 3,
    ...Platform.select({
      ios: { shadowColor: '#0F172A', shadowOffset: { width: 2, height: 4 }, shadowOpacity: 0.22, shadowRadius: 10 },
      android: { elevation: 8 },
    }),
  },
  categorySpinSemiFabGrad: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  categorySpinSemiFabIcon: {
    marginLeft: 5,
  },
  categorySpinWheelColumn: {
    position: 'absolute',
    alignItems: 'center',
    zIndex: 1,
  },
  categorySpinWheelWrap: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categorySpinWheelHalo: {
    position: 'absolute',
    top: -8,
    left: -8,
    width: 184,
    height: 184,
    borderRadius: 92,
    borderWidth: 2,
    borderColor: `${themeColors.primary}55`,
    backgroundColor: 'transparent',
  },
  categorySpinWheelPointerRow: {
    position: 'absolute',
    top: -2,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 6,
  },
  categorySpinWheelPointer: {
    width: 0,
    height: 0,
    borderLeftWidth: 11,
    borderRightWidth: 11,
    borderTopWidth: 16,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#0F172A',
  },
  categorySpinMapLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 6,
    marginTop: 10,
    paddingHorizontal: 4,
  },
  categorySpinMapLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(226,232,240,0.95)',
  },
  categorySpinMapLegendText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#475569',
    maxWidth: 72,
  },
  categorySpinMapCaption: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '800',
    color: '#1E293B',
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 6,
  },

  // Khalid plan-generation scout loader (mosaic + pop-in photos)
  scoutMosaicStage: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 10,
  },
  scoutMosaicInner: {
    position: 'relative',
    overflow: 'visible',
  },
  scoutMosaicPrefetching: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 20,
    zIndex: 20,
  },
  scoutMosaicPrefetchingSheet: {
    backgroundColor: 'rgba(200,16,46,0.05)',
  },
  scoutMosaicCell: {
    position: 'absolute',
    overflow: 'hidden',
    borderWidth: 2.5,
    borderColor: 'rgba(255,255,255,0.92)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.22,
        shadowRadius: 8,
      },
      android: { elevation: 6 },
    }),
  },
  scoutMosaicCellSheet: {
    borderColor: 'rgba(200,16,46,0.35)',
    ...Platform.select({
      ios: {
        shadowColor: themeColors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
      },
      android: { elevation: 3 },
    }),
  },
  scoutMosaicCellBack: {
    borderColor: 'rgba(255,255,255,0.5)',
    ...Platform.select({
      ios: { shadowOpacity: 0.12, shadowRadius: 5, shadowOffset: { width: 0, height: 2 } },
      android: {},
    }),
  },
  scoutMosaicCellBackSheet: {
    borderColor: 'rgba(200,16,46,0.22)',
  },
  scoutMosaicCellHero: {
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.98)',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.38,
        shadowRadius: 16,
      },
      android: {},
    }),
  },
  scoutMosaicCellHeroSheet: {
    borderColor: 'rgba(200,16,46,0.45)',
    ...Platform.select({
      ios: {
        shadowColor: themeColors.primary,
        shadowOpacity: 0.22,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
      },
      android: {},
    }),
  },
  scoutMosaicCellShine: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    pointerEvents: 'none',
  },
  scoutMosaicEmpty: {
    width: Math.min(SCREEN_WIDTH - 24, 400),
    height: 200,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
  },
  scoutMosaicEmptySheet: {
    width: '100%',
    maxWidth: 360,
    height: 168,
    backgroundColor: 'rgba(200,16,46,0.06)',
    borderColor: 'rgba(200,16,46,0.14)',
  },
  scoutMosaicEmptyText: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.72)',
    textAlign: 'center',
  },
  scoutMosaicEmptyTextSheet: {
    color: '#64748B',
  },
  scoutChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 10,
    marginBottom: 2,
  },
  scoutChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.32)',
  },
  scoutChipSheet: {
    backgroundColor: 'rgba(200,16,46,0.08)',
    borderColor: 'rgba(200,16,46,0.18)',
  },
  scoutChipText: {
    fontSize: 11,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.88)',
    letterSpacing: 0.2,
  },
  scoutChipTextSheet: {
    color: '#64748B',
  },
  loadingScoutTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
    letterSpacing: -0.3,
    marginBottom: 6,
    lineHeight: 24,
  },
  loadingScoutTitleAccent: {
    color: themeColors.primary,
    fontWeight: '900',
  },
  loadingScoutSub: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
})

export default styles
